name: veryl

on:
  push:
  pull_request:

jobs:
  veryl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: veryl-lang/setup-veryl@v1
      - name: Format check
        run: veryl fmt --check
      - name: Semantic check
        run: veryl check
      - name: Test (native simulator)
        run: veryl test
      - name: Build (transpile to SystemVerilog)
        run: veryl build
